# Generated by Django 5.2.4 on 2025-07-16 07:54

import blog.models
import django.db.models.deletion
import django_ckeditor_5.fields
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.blogcategory', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی بلاگ',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای بلاگ',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3000, verbose_name='عنوان')),
                ('slug', models.TextField(help_text='اسلاگ باید به صورت دستی وارد شود و می\u200cتواند شامل حروف فارسی، انگلیسی، اعداد، خط تیره یا زیرخط باشد.', verbose_name='اسلاگ')),
                ('reading_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='زمان مطالعه')),
                ('thumbnail', models.ImageField(upload_to=blog.models.blog_thumbnail_upload_to, verbose_name='تصویر کاور')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='مقدمه')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='محتوا')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'پست بلاگ',
                'verbose_name_plural': 'پست\u200cهای بلاگ',
                'ordering': ['-created_at'],
            },
        ),
    ]
