# Generated by Django 5.2.4 on 2025-07-16 07:54

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='catalogs/', verbose_name='فایل PDF کاتالوگ')),
            ],
            options={
                'verbose_name': 'کاتالوگ',
                'verbose_name_plural': 'کاتالوگ',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیحات')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'اطلاعات تماس',
            },
        ),
        migrations.CreateModel(
            name='ExpertsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='واحد')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره ثابت')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن همراه')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='آیدی تلگرام')),
                ('profile', models.ImageField(upload_to='home/experts', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'متخصص',
                'verbose_name_plural': 'متخصصین',
            },
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='عنوان')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیحات')),
                ('footer_text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='متن پایانی')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/about_us/', verbose_name='تصویر')),
                ('video', models.FileField(blank=True, null=True, upload_to='home/about_us/', verbose_name='ویدیو')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order'], name='home_aboutu_order_1e83f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/sliders/', verbose_name='تصویر')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'اسلایدر صفحه اصلی',
                'verbose_name_plural': 'اسلایدرهای صفحه اصلی',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order'], name='home_homesl_order_ac4f0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/gallery/images/', verbose_name='عکس')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.gallerysection', verbose_name='بخش گالری')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'تصاویر گالری',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order'], name='home_galler_order_fd5b1a_idx')],
            },
        ),
    ]
